# https://kubernetes.io/docs/concepts/configuration/configmap/
apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-conf
#  namespace: default
data:
  env: |
    MONGO_DSN=
    KAFKA_CLIENT_ID=
    KAFKA_BROKER=
    KAFKA_CONSUMER_GROUP_ID=
    KAFKA_SASL_USERNAME=
